package org.bentoweb.amfortas.hibernate.om;

import java.util.Set;


/**
 * AssistiveTechnologyTypes generated by hbm2java
 */

public class AssistiveTechnologyTypes  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -611722184129085197L;
	private Integer assistiveTechnologyTypesId;
     private String nameKey;
     private String nameDefault;
     private Set assistiveTechnologies;


    // Constructors

    /** default constructor */
    public AssistiveTechnologyTypes() {
    }
    
    /** constructor with id */
    public AssistiveTechnologyTypes(Integer assistiveTechnologyTypesId) {
        this.assistiveTechnologyTypesId = assistiveTechnologyTypesId;
    }

    

   
    // Property accessors

    public Integer getAssistiveTechnologyTypesId() {
        return this.assistiveTechnologyTypesId;
    }
    
    public void setAssistiveTechnologyTypesId(Integer assistiveTechnologyTypesId) {
        this.assistiveTechnologyTypesId = assistiveTechnologyTypesId;
    }

    public String getNameKey() {
        return this.nameKey;
    }
    
    public void setNameKey(String nameKey) {
        this.nameKey = nameKey;
    }

    public String getNameDefault() {
        return this.nameDefault;
    }
    
    public void setNameDefault(String nameDefault) {
        this.nameDefault = nameDefault;
    }

    public Set getAssistiveTechnologies() {
        return this.assistiveTechnologies;
    }
    
    public void setAssistiveTechnologies(Set assistiveTechnologies) {
        this.assistiveTechnologies = assistiveTechnologies;
    }
   








}