package org.bentoweb.amfortas.hibernate.om;

import java.util.Set;


/**
 * AtExperience generated by hbm2java
 */

public class AtExperience  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 71548553720548600L;
	private Integer atExperienceId;
     private String nameKey;
     private String nameDefault;
     private Set userUsesAssistiveTechnologies;
     private Set userUsesDevices;
     private Set userUsesUserAgents;


    // Constructors

    /** default constructor */
    public AtExperience() {
    }
    
    /** constructor with id */
    public AtExperience(Integer atExperienceId) {
        this.atExperienceId = atExperienceId;
    }

    

   
    // Property accessors

    public Integer getAtExperienceId() {
        return this.atExperienceId;
    }
    
    public void setAtExperienceId(Integer atExperienceId) {
        this.atExperienceId = atExperienceId;
    }

    public String getNameKey() {
        return this.nameKey;
    }
    
    public void setNameKey(String nameKey) {
        this.nameKey = nameKey;
    }

    public String getNameDefault() {
        return this.nameDefault;
    }
    
    public void setNameDefault(String nameDefault) {
        this.nameDefault = nameDefault;
    }

    public Set getUserUsesAssistiveTechnologies() {
        return this.userUsesAssistiveTechnologies;
    }
    
    public void setUserUsesAssistiveTechnologies(Set userUsesAssistiveTechnologies) {
        this.userUsesAssistiveTechnologies = userUsesAssistiveTechnologies;
    }

    public Set getUserUsesDevices() {
        return this.userUsesDevices;
    }
    
    public void setUserUsesDevices(Set userUsesDevices) {
        this.userUsesDevices = userUsesDevices;
    }

    public Set getUserUsesUserAgents() {
        return this.userUsesUserAgents;
    }
    
    public void setUserUsesUserAgents(Set userUsesUserAgents) {
        this.userUsesUserAgents = userUsesUserAgents;
    }
   








}