package org.bentoweb.amfortas.hibernate.om;

import java.util.Set;


/**
 * Device generated by hbm2java
 */

public class Device  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 8094448341467097996L;
	private Integer deviceId;
     private String nameKey;
     private String nameDefault;
     private Set userUsesDevices;


    // Constructors

    /** default constructor */
    public Device() {
    }
    
    /** constructor with id */
    public Device(Integer deviceId) {
        this.deviceId = deviceId;
    }

    

   
    // Property accessors

    public Integer getDeviceId() {
        return this.deviceId;
    }
    
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    public String getNameKey() {
        return this.nameKey;
    }
    
    public void setNameKey(String nameKey) {
        this.nameKey = nameKey;
    }

    public String getNameDefault() {
        return this.nameDefault;
    }
    
    public void setNameDefault(String nameDefault) {
        this.nameDefault = nameDefault;
    }

    public Set getUserUsesDevices() {
        return this.userUsesDevices;
    }
    
    public void setUserUsesDevices(Set userUsesDevices) {
        this.userUsesDevices = userUsesDevices;
    }
   








}