package org.bentoweb.amfortas.hibernate.om;

import java.util.Set;


/**
 * Disability generated by hbm2java
 */

public class Disability  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -5272845706750132003L;
	private Integer disabilityId;
     private String nameKey;
     private String nameDefault;
     private Set userProfileHasDisabilities;


    // Constructors

    /** default constructor */
    public Disability() {
    }
    
    /** constructor with id */
    public Disability(Integer disabilityId) {
        this.disabilityId = disabilityId;
    }

    

   
    // Property accessors

    public Integer getDisabilityId() {
        return this.disabilityId;
    }
    
    public void setDisabilityId(Integer disabilityId) {
        this.disabilityId = disabilityId;
    }

    public String getNameKey() {
        return this.nameKey;
    }
    
    public void setNameKey(String nameKey) {
        this.nameKey = nameKey;
    }

    public String getNameDefault() {
        return this.nameDefault;
    }
    
    public void setNameDefault(String nameDefault) {
        this.nameDefault = nameDefault;
    }

    public Set getUserProfileHasDisabilities() {
        return this.userProfileHasDisabilities;
    }
    
    public void setUserProfileHasDisabilities(Set userProfileHasDisabilities) {
        this.userProfileHasDisabilities = userProfileHasDisabilities;
    }
   








}