package org.bentoweb.amfortas.hibernate.om;



/**
 * HeaderLog generated by hbm2java
 */

public class HeaderLog  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -7379245100209439479L;
	private Integer headerLogId;
     private Testresult testresult;
     private String headerKey;
     private String headerValue;


    // Constructors

    /** default constructor */
    public HeaderLog() {
    }
    
    /** constructor with id */
    public HeaderLog(Integer headerLogId) {
        this.headerLogId = headerLogId;
    }

    

   
    // Property accessors

    public Integer getHeaderLogId() {
        return this.headerLogId;
    }
    
    public void setHeaderLogId(Integer headerLogId) {
        this.headerLogId = headerLogId;
    }

    public Testresult getTestresult() {
        return this.testresult;
    }
    
    public void setTestresult(Testresult testresult) {
        this.testresult = testresult;
    }

    public String getHeaderKey() {
        return this.headerKey;
    }
    
    public void setHeaderKey(String headerKey) {
        this.headerKey = headerKey;
    }

    public String getHeaderValue() {
        return this.headerValue;
    }
    
    public void setHeaderValue(String headerValue) {
        this.headerValue = headerValue;
    }
   








}