package org.bentoweb.amfortas.hibernate.om;

import java.util.Set;


/**
 * LanguageExperience generated by hbm2java
 */

public class LanguageExperience  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 3190670029290905145L;
	private Integer languageExperienceId;
     private String nameKey;
     private String nameDefault;
     private Set userProfiles;


    // Constructors

    /** default constructor */
    public LanguageExperience() {
    }
    
    /** constructor with id */
    public LanguageExperience(Integer languageExperienceId) {
        this.languageExperienceId = languageExperienceId;
    }

    

   
    // Property accessors

    public Integer getLanguageExperienceId() {
        return this.languageExperienceId;
    }
    
    public void setLanguageExperienceId(Integer languageExperienceId) {
        this.languageExperienceId = languageExperienceId;
    }

    public String getNameKey() {
        return this.nameKey;
    }
    
    public void setNameKey(String nameKey) {
        this.nameKey = nameKey;
    }

    public String getNameDefault() {
        return this.nameDefault;
    }
    
    public void setNameDefault(String nameDefault) {
        this.nameDefault = nameDefault;
    }

    public Set getUserProfiles() {
        return this.userProfiles;
    }
    
    public void setUserProfiles(Set userProfiles) {
        this.userProfiles = userProfiles;
    }
   








}