package org.bentoweb.amfortas.hibernate.om;

import java.util.Set;


/**
 * Language generated by hbm2java
 */

public class Language  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 6843618570791771224L;
	private Integer languageId;
     private String nameKey;
     private String nameDefault;
     private String shortcode;
     private Set users;


    // Constructors

    /** default constructor */
    public Language() {
    }
    
    /** constructor with id */
    public Language(Integer languageId) {
        this.languageId = languageId;
    }

    

   
    // Property accessors

    public Integer getLanguageId() {
        return this.languageId;
    }
    
    public void setLanguageId(Integer languageId) {
        this.languageId = languageId;
    }

    public String getNameKey() {
        return this.nameKey;
    }
    
    public void setNameKey(String nameKey) {
        this.nameKey = nameKey;
    }

    public String getNameDefault() {
        return this.nameDefault;
    }
    
    public void setNameDefault(String nameDefault) {
        this.nameDefault = nameDefault;
    }

    public String getShortcode() {
        return this.shortcode;
    }
    
    public void setShortcode(String shortcode) {
        this.shortcode = shortcode;
    }

    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }
   








}