package org.bentoweb.amfortas.hibernate.om;



/**
 * Likertscale generated by hbm2java
 */

public class Likertscale  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -6869902116602963043L;
	private Integer likertId;
     private Testresult testresult;
     private Integer level;


    // Constructors

    /** default constructor */
    public Likertscale() {
    }
    
    /** constructor with id */
    public Likertscale(Integer likertId) {
        this.likertId = likertId;
    }

    

   
    // Property accessors

    public Integer getLikertId() {
        return this.likertId;
    }
    
    public void setLikertId(Integer likertId) {
        this.likertId = likertId;
    }

    public Testresult getTestresult() {
        return this.testresult;
    }
    
    public void setTestresult(Testresult testresult) {
        this.testresult = testresult;
    }

    public Integer getLevel() {
        return this.level;
    }
    
    public void setLevel(Integer level) {
        this.level = level;
    }
   








}