package org.bentoweb.amfortas.hibernate.om;



/**
 * Multiplechoice generated by hbm2java
 */

public class Multiplechoice  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 187769137418527522L;
	private Integer multipleId;
     private Testresult testresult;
     private Integer level;


    // Constructors

    /** default constructor */
    public Multiplechoice() {
    }
    
    /** constructor with id */
    public Multiplechoice(Integer multipleId) {
        this.multipleId = multipleId;
    }

    

   
    // Property accessors

    public Integer getMultipleId() {
        return this.multipleId;
    }
    
    public void setMultipleId(Integer multipleId) {
        this.multipleId = multipleId;
    }

    public Testresult getTestresult() {
        return this.testresult;
    }
    
    public void setTestresult(Testresult testresult) {
        this.testresult = testresult;
    }

    public Integer getLevel() {
        return this.level;
    }
    
    public void setLevel(Integer level) {
        this.level = level;
    }
   








}