package org.bentoweb.amfortas.hibernate.om;



/**
 * Openquestion generated by hbm2java
 */

public class Openquestion  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -5736891662736053394L;
	private Integer openId;
     private Testresult testresult;
     private String text;


    // Constructors

    /** default constructor */
    public Openquestion() {
    }
    
    /** constructor with id */
    public Openquestion(Integer openId) {
        this.openId = openId;
    }

    

   
    // Property accessors

    public Integer getOpenId() {
        return this.openId;
    }
    
    public void setOpenId(Integer openId) {
        this.openId = openId;
    }

    public Testresult getTestresult() {
        return this.testresult;
    }
    
    public void setTestresult(Testresult testresult) {
        this.testresult = testresult;
    }

    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
   








}