package org.bentoweb.amfortas.hibernate.om;

import java.util.Set;


/**
 * OperatingSystemSetting generated by hbm2java
 */

public class OperatingSystemSetting  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 1768494261468377507L;
	private Integer operatingSystemSettingId;
     private String nameKey;
     private String nameDefault;
     private Set userUsesOsSettings;


    // Constructors

    /** default constructor */
    public OperatingSystemSetting() {
    }
    
    /** constructor with id */
    public OperatingSystemSetting(Integer operatingSystemSettingId) {
        this.operatingSystemSettingId = operatingSystemSettingId;
    }

    

   
    // Property accessors

    public Integer getOperatingSystemSettingId() {
        return this.operatingSystemSettingId;
    }
    
    public void setOperatingSystemSettingId(Integer operatingSystemSettingId) {
        this.operatingSystemSettingId = operatingSystemSettingId;
    }

    public String getNameKey() {
        return this.nameKey;
    }
    
    public void setNameKey(String nameKey) {
        this.nameKey = nameKey;
    }

    public String getNameDefault() {
        return this.nameDefault;
    }
    
    public void setNameDefault(String nameDefault) {
        this.nameDefault = nameDefault;
    }

    public Set getUserUsesOsSettings() {
        return this.userUsesOsSettings;
    }
    
    public void setUserUsesOsSettings(Set userUsesOsSettings) {
        this.userUsesOsSettings = userUsesOsSettings;
    }
   








}