package org.bentoweb.amfortas.hibernate.om;

import java.util.Set;


/**
 * OperatingSystem generated by hbm2java
 */

public class OperatingSystem  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -3329838136601069709L;
	private Integer operationgSystemId;
     private String nameKey;
     private String nameDefault;
     private String vendor;
     private Set userUsesOses;


    // Constructors

    /** default constructor */
    public OperatingSystem() {
    }
    
    /** constructor with id */
    public OperatingSystem(Integer operationgSystemId) {
        this.operationgSystemId = operationgSystemId;
    }

    

   
    // Property accessors

    public Integer getOperationgSystemId() {
        return this.operationgSystemId;
    }
    
    public void setOperationgSystemId(Integer operationgSystemId) {
        this.operationgSystemId = operationgSystemId;
    }

    public String getNameKey() {
        return this.nameKey;
    }
    
    public void setNameKey(String nameKey) {
        this.nameKey = nameKey;
    }

    public String getNameDefault() {
        return this.nameDefault;
    }
    
    public void setNameDefault(String nameDefault) {
        this.nameDefault = nameDefault;
    }

    public String getVendor() {
        return this.vendor;
    }
    
    public void setVendor(String vendor) {
        this.vendor = vendor;
    }

    public Set getUserUsesOses() {
        return this.userUsesOses;
    }
    
    public void setUserUsesOses(Set userUsesOses) {
        this.userUsesOses = userUsesOses;
    }
   








}