package org.bentoweb.amfortas.hibernate.om;

import java.util.Set;


/**
 * Sex generated by hbm2java
 */

public class Sex  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -7289450674754649112L;
	private Integer sexId;
     private String nameKey;
     private String nameDefault;
     private Set users;


    // Constructors

    /** default constructor */
    public Sex() {
    }
    
    /** constructor with id */
    public Sex(Integer sexId) {
        this.sexId = sexId;
    }

    

   
    // Property accessors

    public Integer getSexId() {
        return this.sexId;
    }
    
    public void setSexId(Integer sexId) {
        this.sexId = sexId;
    }

    public String getNameKey() {
        return this.nameKey;
    }
    
    public void setNameKey(String nameKey) {
        this.nameKey = nameKey;
    }

    public String getNameDefault() {
        return this.nameDefault;
    }
    
    public void setNameDefault(String nameDefault) {
        this.nameDefault = nameDefault;
    }

    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }
   








}