package org.bentoweb.amfortas.hibernate.om;



/**
 * TestProfileHasUserProfileId generated by hbm2java
 */

public class TestProfileHasUserProfileId  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -7555157662803612487L;
	private Integer testProfileId;
     private Integer userProfileId;


    // Constructors

    /** default constructor */
    public TestProfileHasUserProfileId() {
    }
    

    

   
    // Property accessors

    public Integer getTestProfileId() {
        return this.testProfileId;
    }
    
    public void setTestProfileId(Integer testProfileId) {
        this.testProfileId = testProfileId;
    }

    public Integer getUserProfileId() {
        return this.userProfileId;
    }
    
    public void setUserProfileId(Integer userProfileId) {
        this.userProfileId = userProfileId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TestProfileHasUserProfileId) ) return false;
		 TestProfileHasUserProfileId castOther = ( TestProfileHasUserProfileId ) other; 
         
		 return ( (this.getTestProfileId()==castOther.getTestProfileId()) || ( this.getTestProfileId()!=null && castOther.getTestProfileId()!=null && this.getTestProfileId().equals(castOther.getTestProfileId()) ) )
 && ( (this.getUserProfileId()==castOther.getUserProfileId()) || ( this.getUserProfileId()!=null && castOther.getUserProfileId()!=null && this.getUserProfileId().equals(castOther.getUserProfileId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTestProfileId() == null ? 0 : this.getTestProfileId().hashCode() );
         result = 37 * result + ( getUserProfileId() == null ? 0 : this.getUserProfileId().hashCode() );
         return result;
   }   





}