package org.bentoweb.amfortas.hibernate.om;

import java.util.Date;
import java.util.Set;


/**
 * TestProfile generated by hbm2java
 */

public class TestProfile  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -6053651767631450912L;
	private Integer testProfileId;
     private User user;
     private UserUsesOs userUsesOs;
     private UserUsesDevice userUsesDevice;
     private boolean isActive;
     private Date dateCreation;
     private Date lastLogin;
     private Set userUsesUserAgents;
     private Set userUsesAssistiveTechnologies;
     private Set testcaseSets;
     private Set testresults;
     private Set testProfileHasTestSuites;
     private Set testProfileHasUserProfiles;


    // Constructors

    /** default constructor */
    public TestProfile() {
    }
    
    /** constructor with id */
    public TestProfile(Integer testProfileId) {
        this.testProfileId = testProfileId;
    }

    

   
    // Property accessors

    public Integer getTestProfileId() {
        return this.testProfileId;
    }
    
    public void setTestProfileId(Integer testProfileId) {
        this.testProfileId = testProfileId;
    }

    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    public UserUsesOs getUserUsesOs() {
        return this.userUsesOs;
    }
    
    public void setUserUsesOs(UserUsesOs userUsesOs) {
        this.userUsesOs = userUsesOs;
    }

    public UserUsesDevice getUserUsesDevice() {
        return this.userUsesDevice;
    }
    
    public void setUserUsesDevice(UserUsesDevice userUsesDevice) {
        this.userUsesDevice = userUsesDevice;
    }

    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

    public Date getDateCreation() {
        return this.dateCreation;
    }
    
    public void setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }

    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    public Set getUserUsesUserAgents() {
        return this.userUsesUserAgents;
    }
    
    public void setUserUsesUserAgents(Set userUsesUserAgents) {
        this.userUsesUserAgents = userUsesUserAgents;
    }

    public Set getUserUsesAssistiveTechnologies() {
        return this.userUsesAssistiveTechnologies;
    }
    
    public void setUserUsesAssistiveTechnologies(Set userUsesAssistiveTechnologies) {
        this.userUsesAssistiveTechnologies = userUsesAssistiveTechnologies;
    }

    public Set getTestcaseSets() {
        return this.testcaseSets;
    }
    
    public void setTestcaseSets(Set testcaseSets) {
        this.testcaseSets = testcaseSets;
    }

    public Set getTestresults() {
        return this.testresults;
    }
    
    public void setTestresults(Set testresults) {
        this.testresults = testresults;
    }

    public Set getTestProfileHasTestSuites() {
        return this.testProfileHasTestSuites;
    }
    
    public void setTestProfileHasTestSuites(Set testProfileHasTestSuites) {
        this.testProfileHasTestSuites = testProfileHasTestSuites;
    }

    public Set getTestProfileHasUserProfiles() {
        return this.testProfileHasUserProfiles;
    }
    
    public void setTestProfileHasUserProfiles(Set testProfileHasUserProfiles) {
        this.testProfileHasUserProfiles = testProfileHasUserProfiles;
    }
   








}