package org.bentoweb.amfortas.hibernate.om;



/**
 * TestProfileHasTestSuiteId generated by hbm2java
 */

public class TestProfileHasTestSuiteId  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -5222368481901497003L;
	private Integer testProfileId;
     private Integer testSuiteId;


    // Constructors

    /** default constructor */
    public TestProfileHasTestSuiteId() {
    }
    

    

   
    // Property accessors

    public Integer getTestProfileId() {
        return this.testProfileId;
    }
    
    public void setTestProfileId(Integer testProfileId) {
        this.testProfileId = testProfileId;
    }

    public Integer getTestSuiteId() {
        return this.testSuiteId;
    }
    
    public void setTestSuiteId(Integer testSuiteId) {
        this.testSuiteId = testSuiteId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TestProfileHasTestSuiteId) ) return false;
		 TestProfileHasTestSuiteId castOther = ( TestProfileHasTestSuiteId ) other; 
         
		 return ( (this.getTestProfileId()==castOther.getTestProfileId()) || ( this.getTestProfileId()!=null && castOther.getTestProfileId()!=null && this.getTestProfileId().equals(castOther.getTestProfileId()) ) )
 && ( (this.getTestSuiteId()==castOther.getTestSuiteId()) || ( this.getTestSuiteId()!=null && castOther.getTestSuiteId()!=null && this.getTestSuiteId().equals(castOther.getTestSuiteId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTestProfileId() == null ? 0 : this.getTestProfileId().hashCode() );
         result = 37 * result + ( getTestSuiteId() == null ? 0 : this.getTestSuiteId().hashCode() );
         return result;
   }   





}