package org.bentoweb.amfortas.hibernate.om;



/**
 * TestProfileHasUserProfile generated by hbm2java
 */

public class TestProfileHasUserProfile  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 8827094855443787283L;
	private TestProfileHasUserProfileId id;
     private TestProfile testProfile;
     private UserProfile userProfile;


    // Constructors

    /** default constructor */
    public TestProfileHasUserProfile() {
    }
    
    /** constructor with id */
    public TestProfileHasUserProfile(TestProfileHasUserProfileId id) {
        this.id = id;
    }

    

   
    // Property accessors

    public TestProfileHasUserProfileId getId() {
        return this.id;
    }
    
    public void setId(TestProfileHasUserProfileId id) {
        this.id = id;
    }

    public TestProfile getTestProfile() {
        return this.testProfile;
    }
    
    public void setTestProfile(TestProfile testProfile) {
        this.testProfile = testProfile;
    }

    public UserProfile getUserProfile() {
        return this.userProfile;
    }
    
    public void setUserProfile(UserProfile userProfile) {
        this.userProfile = userProfile;
    }
   








}