package org.bentoweb.amfortas.hibernate.om;

import java.util.Date;


/**
 * TestcasePool generated by hbm2java
 */

public class TestcasePool  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 8562998187619828218L;
	private Integer testcasePoolId;
     private TestcaseSet testcaseSet;
     private String testcaseId;
     private String scenarioId;
     private Date dateStart;
     private Date dateFinished;
     private boolean finished;


    // Constructors

    /** default constructor */
    public TestcasePool() {
    }
    
    /** constructor with id */
    public TestcasePool(Integer testcasePoolId) {
        this.testcasePoolId = testcasePoolId;
    }

    

   
    // Property accessors

    public Integer getTestcasePoolId() {
        return this.testcasePoolId;
    }
    
    public void setTestcasePoolId(Integer testcasePoolId) {
        this.testcasePoolId = testcasePoolId;
    }

    public TestcaseSet getTestcaseSet() {
        return this.testcaseSet;
    }
    
    public void setTestcaseSet(TestcaseSet testcaseSet) {
        this.testcaseSet = testcaseSet;
    }

    public String getTestcaseId() {
        return this.testcaseId;
    }
    
    public void setTestcaseId(String testcaseId) {
        this.testcaseId = testcaseId;
    }

    public String getScenarioId() {
        return this.scenarioId;
    }
    
    public void setScenarioId(String scenarioId) {
        this.scenarioId = scenarioId;
    }

    public Date getDateStart() {
        return this.dateStart;
    }
    
    public void setDateStart(Date dateStart) {
        this.dateStart = dateStart;
    }

    public Date getDateFinished() {
        return this.dateFinished;
    }
    
    public void setDateFinished(Date dateFinished) {
        this.dateFinished = dateFinished;
    }

    public boolean isFinished() {
        return this.finished;
    }
    
    public void setFinished(boolean finished) {
        this.finished = finished;
    }
   








}