package org.bentoweb.amfortas.hibernate.om;

import java.util.Date;
import java.util.Set;


/**
 * TestcaseSet generated by hbm2java
 */

public class TestcaseSet  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 6555325347789181687L;
	private Integer testcaseSetId;
     private TestSuite testSuite;
     private TestProfile testProfile;
     private Date dateCreation;
     private boolean done;
     private Set testcasePools;


    // Constructors

    /** default constructor */
    public TestcaseSet() {
    }
    
    /** constructor with id */
    public TestcaseSet(Integer testcaseSetId) {
        this.testcaseSetId = testcaseSetId;
    }

    

   
    // Property accessors

    public Integer getTestcaseSetId() {
        return this.testcaseSetId;
    }
    
    public void setTestcaseSetId(Integer testcaseSetId) {
        this.testcaseSetId = testcaseSetId;
    }

    public TestSuite getTestSuite() {
        return this.testSuite;
    }
    
    public void setTestSuite(TestSuite testSuite) {
        this.testSuite = testSuite;
    }

    public TestProfile getTestProfile() {
        return this.testProfile;
    }
    
    public void setTestProfile(TestProfile testProfile) {
        this.testProfile = testProfile;
    }

    public Date getDateCreation() {
        return this.dateCreation;
    }
    
    public void setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }

    public boolean isDone() {
        return this.done;
    }
    
    public void setDone(boolean done) {
        this.done = done;
    }

    public Set getTestcasePools() {
        return this.testcasePools;
    }
    
    public void setTestcasePools(Set testcasePools) {
        this.testcasePools = testcasePools;
    }
   








}