package org.bentoweb.amfortas.hibernate.om;

import java.util.Date;
import java.util.Set;


/**
 * TestSuite generated by hbm2java
 */

public class TestSuite  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 558220153189124165L;
	private Integer testSuiteId;
     private String title;
     private String description;
     private String indexFileUri;
     private String metadataFilesUri;
     private String testFilesUri;
     private String mappingFileUri;
     private Integer timesPerTestCase;
     private Integer testCasesPerUser;
     private Date dateStart;
     private Date dateEnd;
     private boolean isActive;
     private byte[] object;
     private Set testcaseSets;
     private Set testProfileHasTestSuites;
     private Set testresults;


    // Constructors

    /** default constructor */
    public TestSuite() {
    }
    
    /** constructor with id */
    public TestSuite(Integer testSuiteId) {
        this.testSuiteId = testSuiteId;
    }

    

   
    // Property accessors

    public Integer getTestSuiteId() {
        return this.testSuiteId;
    }
    
    public void setTestSuiteId(Integer testSuiteId) {
        this.testSuiteId = testSuiteId;
    }

    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getIndexFileUri() {
        return this.indexFileUri;
    }
    
    public void setIndexFileUri(String indexFileUri) {
        this.indexFileUri = indexFileUri;
    }

    public String getMetadataFilesUri() {
        return this.metadataFilesUri;
    }
    
    public void setMetadataFilesUri(String metadataFilesUri) {
        this.metadataFilesUri = metadataFilesUri;
    }

    public String getTestFilesUri() {
        return this.testFilesUri;
    }
    
    public void setTestFilesUri(String testFilesUri) {
        this.testFilesUri = testFilesUri;
    }

    public String getMappingFileUri() {
        return this.mappingFileUri;
    }
    
    public void setMappingFileUri(String mappingFileUri) {
        this.mappingFileUri = mappingFileUri;
    }

    public Integer getTimesPerTestCase() {
        return this.timesPerTestCase;
    }
    
    public void setTimesPerTestCase(Integer timesPerTestCase) {
        this.timesPerTestCase = timesPerTestCase;
    }

    public Integer getTestCasesPerUser() {
        return this.testCasesPerUser;
    }
    
    public void setTestCasesPerUser(Integer testCasesPerUser) {
        this.testCasesPerUser = testCasesPerUser;
    }

    public Date getDateStart() {
        return this.dateStart;
    }
    
    public void setDateStart(Date dateStart) {
        this.dateStart = dateStart;
    }

    public Date getDateEnd() {
        return this.dateEnd;
    }
    
    public void setDateEnd(Date dateEnd) {
        this.dateEnd = dateEnd;
    }

    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

    public byte[] getObject() {
        return this.object;
    }
    
    public void setObject(byte[] object) {
        this.object = object;
    }

    public Set getTestcaseSets() {
        return this.testcaseSets;
    }
    
    public void setTestcaseSets(Set testcaseSets) {
        this.testcaseSets = testcaseSets;
    }

    public Set getTestProfileHasTestSuites() {
        return this.testProfileHasTestSuites;
    }
    
    public void setTestProfileHasTestSuites(Set testProfileHasTestSuites) {
        this.testProfileHasTestSuites = testProfileHasTestSuites;
    }

    public Set getTestresults() {
        return this.testresults;
    }
    
    public void setTestresults(Set testresults) {
        this.testresults = testresults;
    }
   








}