package org.bentoweb.amfortas.hibernate.om;

import java.util.Date;
import java.util.Set;


/**
 * Testresult generated by hbm2java
 */

public class Testresult  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -6613410903813408170L;
	private Integer testresultId;
     private TestSuite testSuite;
     private TestProfile testProfile;
     private UserProfile userProfile;
     private String scenarioId;
     private String testcaseId;
     private Date date;
     private Set openquestions;
     private Set yesnoquestions;
     private Set likertscales;
     private Set headerLogs;
     private Set yesnoopenquestions;
     private Set multiplechoices;


    // Constructors

    /** default constructor */
    public Testresult() {
    }
    
    /** constructor with id */
    public Testresult(Integer testresultId) {
        this.testresultId = testresultId;
    }

    

   
    // Property accessors

    public Integer getTestresultId() {
        return this.testresultId;
    }
    
    public void setTestresultId(Integer testresultId) {
        this.testresultId = testresultId;
    }

    public TestSuite getTestSuite() {
        return this.testSuite;
    }
    
    public void setTestSuite(TestSuite testSuite) {
        this.testSuite = testSuite;
    }

    public TestProfile getTestProfile() {
        return this.testProfile;
    }
    
    public void setTestProfile(TestProfile testProfile) {
        this.testProfile = testProfile;
    }

    public UserProfile getUserProfile() {
        return this.userProfile;
    }
    
    public void setUserProfile(UserProfile userProfile) {
        this.userProfile = userProfile;
    }

    public String getScenarioId() {
        return this.scenarioId;
    }
    
    public void setScenarioId(String scenarioId) {
        this.scenarioId = scenarioId;
    }

    public String getTestcaseId() {
        return this.testcaseId;
    }
    
    public void setTestcaseId(String testcaseId) {
        this.testcaseId = testcaseId;
    }

    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    public Set getOpenquestions() {
        return this.openquestions;
    }
    
    public void setOpenquestions(Set openquestions) {
        this.openquestions = openquestions;
    }

    public Set getYesnoquestions() {
        return this.yesnoquestions;
    }
    
    public void setYesnoquestions(Set yesnoquestions) {
        this.yesnoquestions = yesnoquestions;
    }

    public Set getLikertscales() {
        return this.likertscales;
    }
    
    public void setLikertscales(Set likertscales) {
        this.likertscales = likertscales;
    }

    public Set getHeaderLogs() {
        return this.headerLogs;
    }
    
    public void setHeaderLogs(Set headerLogs) {
        this.headerLogs = headerLogs;
    }

    public Set getYesnoopenquestions() {
        return this.yesnoopenquestions;
    }
    
    public void setYesnoopenquestions(Set yesnoopenquestions) {
        this.yesnoopenquestions = yesnoopenquestions;
    }

    public Set getMultiplechoices() {
        return this.multiplechoices;
    }
    
    public void setMultiplechoices(Set multiplechoices) {
        this.multiplechoices = multiplechoices;
    }
   








}