package org.bentoweb.amfortas.hibernate.om;

import java.util.Date;
import java.util.Set;


/**
 * User generated by hbm2java
 */

public class User  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -7312543512193125814L;
	private Integer userId;
     private Sex sex;
     private Language language;
     private String password;
     private String nameFirst;
     private String nameLast;
     private String email;
     private String languageNativeOther;
     private Date dateRegister;
     private byte statusUser;
     private String mailConfHash;
     private Set userHasRoles;
     private Set testProfiles;


    // Constructors

    /** default constructor */
    public User() {
    }
    
    /** constructor with id */
    public User(Integer userId) {
        this.userId = userId;
    }

    

   
    // Property accessors

    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Sex getSex() {
        return this.sex;
    }
    
    public void setSex(Sex sex) {
        this.sex = sex;
    }

    public Language getLanguage() {
        return this.language;
    }
    
    public void setLanguage(Language language) {
        this.language = language;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String getNameFirst() {
        return this.nameFirst;
    }
    
    public void setNameFirst(String nameFirst) {
        this.nameFirst = nameFirst;
    }

    public String getNameLast() {
        return this.nameLast;
    }
    
    public void setNameLast(String nameLast) {
        this.nameLast = nameLast;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getLanguageNativeOther() {
        return this.languageNativeOther;
    }
    
    public void setLanguageNativeOther(String languageNativeOther) {
        this.languageNativeOther = languageNativeOther;
    }

    public Date getDateRegister() {
        return this.dateRegister;
    }
    
    public void setDateRegister(Date dateRegister) {
        this.dateRegister = dateRegister;
    }

    public byte getStatusUser() {
        return this.statusUser;
    }
    
    public void setStatusUser(byte statusUser) {
        this.statusUser = statusUser;
    }

    public String getMailConfHash() {
        return this.mailConfHash;
    }
    
    public void setMailConfHash(String mailConfHash) {
        this.mailConfHash = mailConfHash;
    }

    public Set getUserHasRoles() {
        return this.userHasRoles;
    }
    
    public void setUserHasRoles(Set userHasRoles) {
        this.userHasRoles = userHasRoles;
    }

    public Set getTestProfiles() {
        return this.testProfiles;
    }
    
    public void setTestProfiles(Set testProfiles) {
        this.testProfiles = testProfiles;
    }
   








}