package org.bentoweb.amfortas.hibernate.om;



/**
 * UserUsesOsSetting generated by hbm2java
 */

public class UserUsesOsSetting  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 2374709755362379067L;
	private UserUsesOsSettingId id;
     private UserUsesOs userUsesOs;
     private OperatingSystemSetting operatingSystemSetting;
     private String settingOther;


    // Constructors

    /** default constructor */
    public UserUsesOsSetting() {
    }
    
    /** constructor with id */
    public UserUsesOsSetting(UserUsesOsSettingId id) {
        this.id = id;
    }

    

   
    // Property accessors

    public UserUsesOsSettingId getId() {
        return this.id;
    }
    
    public void setId(UserUsesOsSettingId id) {
        this.id = id;
    }

    public UserUsesOs getUserUsesOs() {
        return this.userUsesOs;
    }
    
    public void setUserUsesOs(UserUsesOs userUsesOs) {
        this.userUsesOs = userUsesOs;
    }

    public OperatingSystemSetting getOperatingSystemSetting() {
        return this.operatingSystemSetting;
    }
    
    public void setOperatingSystemSetting(OperatingSystemSetting operatingSystemSetting) {
        this.operatingSystemSetting = operatingSystemSetting;
    }

    public String getSettingOther() {
        return this.settingOther;
    }
    
    public void setSettingOther(String settingOther) {
        this.settingOther = settingOther;
    }
   








}