package org.bentoweb.amfortas.hibernate.om;



/**
 * UserUsesUaSetting generated by hbm2java
 */

public class UserUsesUaSetting  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -4698441714315387128L;
	private UserUsesUaSettingId id;
     private UserAgentSetting userAgentSetting;
     private UserUsesUserAgent userUsesUserAgent;
     private String settingOther;


    // Constructors

    /** default constructor */
    public UserUsesUaSetting() {
    }
    
    /** constructor with id */
    public UserUsesUaSetting(UserUsesUaSettingId id) {
        this.id = id;
    }

    

   
    // Property accessors

    public UserUsesUaSettingId getId() {
        return this.id;
    }
    
    public void setId(UserUsesUaSettingId id) {
        this.id = id;
    }

    public UserAgentSetting getUserAgentSetting() {
        return this.userAgentSetting;
    }
    
    public void setUserAgentSetting(UserAgentSetting userAgentSetting) {
        this.userAgentSetting = userAgentSetting;
    }

    public UserUsesUserAgent getUserUsesUserAgent() {
        return this.userUsesUserAgent;
    }
    
    public void setUserUsesUserAgent(UserUsesUserAgent userUsesUserAgent) {
        this.userUsesUserAgent = userUsesUserAgent;
    }

    public String getSettingOther() {
        return this.settingOther;
    }
    
    public void setSettingOther(String settingOther) {
        this.settingOther = settingOther;
    }
   








}