package org.bentoweb.amfortas.hibernate.om;

import java.util.Set;


/**
 * UserAgentPlugin generated by hbm2java
 */

public class UserAgentPlugin  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -2350991993623134608L;
	private Integer userAgentPluginId;
     private String nameKey;
     private String nameDefault;
     private String vendor;
     private Set userUsesUaPlugins;


    // Constructors

    /** default constructor */
    public UserAgentPlugin() {
    }
    
    /** constructor with id */
    public UserAgentPlugin(Integer userAgentPluginId) {
        this.userAgentPluginId = userAgentPluginId;
    }

    

   
    // Property accessors

    public Integer getUserAgentPluginId() {
        return this.userAgentPluginId;
    }
    
    public void setUserAgentPluginId(Integer userAgentPluginId) {
        this.userAgentPluginId = userAgentPluginId;
    }

    public String getNameKey() {
        return this.nameKey;
    }
    
    public void setNameKey(String nameKey) {
        this.nameKey = nameKey;
    }

    public String getNameDefault() {
        return this.nameDefault;
    }
    
    public void setNameDefault(String nameDefault) {
        this.nameDefault = nameDefault;
    }

    public String getVendor() {
        return this.vendor;
    }
    
    public void setVendor(String vendor) {
        this.vendor = vendor;
    }

    public Set getUserUsesUaPlugins() {
        return this.userUsesUaPlugins;
    }
    
    public void setUserUsesUaPlugins(Set userUsesUaPlugins) {
        this.userUsesUaPlugins = userUsesUaPlugins;
    }
   








}