package org.bentoweb.amfortas.hibernate.om;

import java.util.Set;


/**
 * UserAgentSetting generated by hbm2java
 */

public class UserAgentSetting  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 444033586556251888L;
	private Integer userAgentSettingId;
     private String nameKey;
     private String nameDefault;
     private Set userUsesUaSettings;


    // Constructors

    /** default constructor */
    public UserAgentSetting() {
    }
    
    /** constructor with id */
    public UserAgentSetting(Integer userAgentSettingId) {
        this.userAgentSettingId = userAgentSettingId;
    }

    

   
    // Property accessors

    public Integer getUserAgentSettingId() {
        return this.userAgentSettingId;
    }
    
    public void setUserAgentSettingId(Integer userAgentSettingId) {
        this.userAgentSettingId = userAgentSettingId;
    }

    public String getNameKey() {
        return this.nameKey;
    }
    
    public void setNameKey(String nameKey) {
        this.nameKey = nameKey;
    }

    public String getNameDefault() {
        return this.nameDefault;
    }
    
    public void setNameDefault(String nameDefault) {
        this.nameDefault = nameDefault;
    }

    public Set getUserUsesUaSettings() {
        return this.userUsesUaSettings;
    }
    
    public void setUserUsesUaSettings(Set userUsesUaSettings) {
        this.userUsesUaSettings = userUsesUaSettings;
    }
   








}