package org.bentoweb.amfortas.hibernate.om;

import java.util.Date;
import java.util.Set;


/**
 * UserProfile generated by hbm2java
 */

public class UserProfile  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -2191752873651909984L;
	private Integer userProfileId;
     private LanguageExperience languageExperience;
     private HoursPerWeek hoursPerWeek;
     private AgeRange ageRange;
     private String disabilityOther;
     private boolean isActive;
     private Date dateCreation;
     private Set testProfileHasUserProfiles;
     private Set userProfileHasDisabilities;
     private Set testresults;


    // Constructors

    /** default constructor */
    public UserProfile() {
    }
    
    /** constructor with id */
    public UserProfile(Integer userProfileId) {
        this.userProfileId = userProfileId;
    }

    

   
    // Property accessors

    public Integer getUserProfileId() {
        return this.userProfileId;
    }
    
    public void setUserProfileId(Integer userProfileId) {
        this.userProfileId = userProfileId;
    }

    public LanguageExperience getLanguageExperience() {
        return this.languageExperience;
    }
    
    public void setLanguageExperience(LanguageExperience languageExperience) {
        this.languageExperience = languageExperience;
    }

    public HoursPerWeek getHoursPerWeek() {
        return this.hoursPerWeek;
    }
    
    public void setHoursPerWeek(HoursPerWeek hoursPerWeek) {
        this.hoursPerWeek = hoursPerWeek;
    }

    public AgeRange getAgeRange() {
        return this.ageRange;
    }
    
    public void setAgeRange(AgeRange ageRange) {
        this.ageRange = ageRange;
    }

    public String getDisabilityOther() {
        return this.disabilityOther;
    }
    
    public void setDisabilityOther(String disabilityOther) {
        this.disabilityOther = disabilityOther;
    }

    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

    public Date getDateCreation() {
        return this.dateCreation;
    }
    
    public void setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }

    public Set getTestProfileHasUserProfiles() {
        return this.testProfileHasUserProfiles;
    }
    
    public void setTestProfileHasUserProfiles(Set testProfileHasUserProfiles) {
        this.testProfileHasUserProfiles = testProfileHasUserProfiles;
    }

    public Set getUserProfileHasDisabilities() {
        return this.userProfileHasDisabilities;
    }
    
    public void setUserProfileHasDisabilities(Set userProfileHasDisabilities) {
        this.userProfileHasDisabilities = userProfileHasDisabilities;
    }

    public Set getTestresults() {
        return this.testresults;
    }
    
    public void setTestresults(Set testresults) {
        this.testresults = testresults;
    }
   








}