package org.bentoweb.amfortas.hibernate.om;



/**
 * UserUsesUaSettingId generated by hbm2java
 */

public class UserUsesUaSettingId  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -1490883639439532141L;
	private Integer userAgentSettingId;
     private Integer userUsesUaId;


    // Constructors

    /** default constructor */
    public UserUsesUaSettingId() {
    }
    

    

   
    // Property accessors

    public Integer getUserAgentSettingId() {
        return this.userAgentSettingId;
    }
    
    public void setUserAgentSettingId(Integer userAgentSettingId) {
        this.userAgentSettingId = userAgentSettingId;
    }

    public Integer getUserUsesUaId() {
        return this.userUsesUaId;
    }
    
    public void setUserUsesUaId(Integer userUsesUaId) {
        this.userUsesUaId = userUsesUaId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserUsesUaSettingId) ) return false;
		 UserUsesUaSettingId castOther = ( UserUsesUaSettingId ) other; 
         
		 return ( (this.getUserAgentSettingId()==castOther.getUserAgentSettingId()) || ( this.getUserAgentSettingId()!=null && castOther.getUserAgentSettingId()!=null && this.getUserAgentSettingId().equals(castOther.getUserAgentSettingId()) ) )
 && ( (this.getUserUsesUaId()==castOther.getUserUsesUaId()) || ( this.getUserUsesUaId()!=null && castOther.getUserUsesUaId()!=null && this.getUserUsesUaId().equals(castOther.getUserUsesUaId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserAgentSettingId() == null ? 0 : this.getUserAgentSettingId().hashCode() );
         result = 37 * result + ( getUserUsesUaId() == null ? 0 : this.getUserUsesUaId().hashCode() );
         return result;
   }   





}