package org.bentoweb.amfortas.hibernate.om;

import java.util.Set;


/**
 * UserUsesOs generated by hbm2java
 */

public class UserUsesOs  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 360171866009351706L;
	private Integer userUsesOsId;
     private OperatingSystem operatingSystem;
     private String version;
     private String osOther;
     private Set userUsesOsSettings;
     private Set testProfiles;


    // Constructors

    /** default constructor */
    public UserUsesOs() {
    }
    
    /** constructor with id */
    public UserUsesOs(Integer userUsesOsId) {
        this.userUsesOsId = userUsesOsId;
    }

    

   
    // Property accessors

    public Integer getUserUsesOsId() {
        return this.userUsesOsId;
    }
    
    public void setUserUsesOsId(Integer userUsesOsId) {
        this.userUsesOsId = userUsesOsId;
    }

    public OperatingSystem getOperatingSystem() {
        return this.operatingSystem;
    }
    
    public void setOperatingSystem(OperatingSystem operatingSystem) {
        this.operatingSystem = operatingSystem;
    }

    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }

    public String getOsOther() {
        return this.osOther;
    }
    
    public void setOsOther(String osOther) {
        this.osOther = osOther;
    }

    public Set getUserUsesOsSettings() {
        return this.userUsesOsSettings;
    }
    
    public void setUserUsesOsSettings(Set userUsesOsSettings) {
        this.userUsesOsSettings = userUsesOsSettings;
    }

    public Set getTestProfiles() {
        return this.testProfiles;
    }
    
    public void setTestProfiles(Set testProfiles) {
        this.testProfiles = testProfiles;
    }
   








}