package org.bentoweb.amfortas.hibernate.om;



/**
 * UserUsesAssistiveTechnology generated by hbm2java
 */

public class UserUsesAssistiveTechnology  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -1525300098114465635L;
	private Integer userUsesAtId;
     private AssistiveTechnology assistiveTechnology;
     private TestProfile testProfile;
     private AtExperience atExperience;
     private String version;
     private String assistiveTechnologyOther;


    // Constructors

    /** default constructor */
    public UserUsesAssistiveTechnology() {
    }
    
    /** constructor with id */
    public UserUsesAssistiveTechnology(Integer userUsesAtId) {
        this.userUsesAtId = userUsesAtId;
    }

    

   
    // Property accessors

    public Integer getUserUsesAtId() {
        return this.userUsesAtId;
    }
    
    public void setUserUsesAtId(Integer userUsesAtId) {
        this.userUsesAtId = userUsesAtId;
    }

    public AssistiveTechnology getAssistiveTechnology() {
        return this.assistiveTechnology;
    }
    
    public void setAssistiveTechnology(AssistiveTechnology assistiveTechnology) {
        this.assistiveTechnology = assistiveTechnology;
    }

    public TestProfile getTestProfile() {
        return this.testProfile;
    }
    
    public void setTestProfile(TestProfile testProfile) {
        this.testProfile = testProfile;
    }

    public AtExperience getAtExperience() {
        return this.atExperience;
    }
    
    public void setAtExperience(AtExperience atExperience) {
        this.atExperience = atExperience;
    }

    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }

    public String getAssistiveTechnologyOther() {
        return this.assistiveTechnologyOther;
    }
    
    public void setAssistiveTechnologyOther(String assistiveTechnologyOther) {
        this.assistiveTechnologyOther = assistiveTechnologyOther;
    }
   








}