package org.bentoweb.amfortas.hibernate.om;



/**
 * UserUsesUaPluginId generated by hbm2java
 */

public class UserUsesUaPluginId  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 5182910295597169038L;
	private Integer userAgentPluginId;
     private Integer userUsesUaId;


    // Constructors

    /** default constructor */
    public UserUsesUaPluginId() {
    }
    

    

   
    // Property accessors

    public Integer getUserAgentPluginId() {
        return this.userAgentPluginId;
    }
    
    public void setUserAgentPluginId(Integer userAgentPluginId) {
        this.userAgentPluginId = userAgentPluginId;
    }

    public Integer getUserUsesUaId() {
        return this.userUsesUaId;
    }
    
    public void setUserUsesUaId(Integer userUsesUaId) {
        this.userUsesUaId = userUsesUaId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserUsesUaPluginId) ) return false;
		 UserUsesUaPluginId castOther = ( UserUsesUaPluginId ) other; 
         
		 return ( (this.getUserAgentPluginId()==castOther.getUserAgentPluginId()) || ( this.getUserAgentPluginId()!=null && castOther.getUserAgentPluginId()!=null && this.getUserAgentPluginId().equals(castOther.getUserAgentPluginId()) ) )
 && ( (this.getUserUsesUaId()==castOther.getUserUsesUaId()) || ( this.getUserUsesUaId()!=null && castOther.getUserUsesUaId()!=null && this.getUserUsesUaId().equals(castOther.getUserUsesUaId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserAgentPluginId() == null ? 0 : this.getUserAgentPluginId().hashCode() );
         result = 37 * result + ( getUserUsesUaId() == null ? 0 : this.getUserUsesUaId().hashCode() );
         return result;
   }   





}