package org.bentoweb.amfortas.hibernate.om;



/**
 * UserProfileHasDisabilityId generated by hbm2java
 */

public class UserProfileHasDisabilityId  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -5623618807151565433L;
	private Integer userProfileId;
     private Integer disabilityId;


    // Constructors

    /** default constructor */
    public UserProfileHasDisabilityId() {
    }
    

    

   
    // Property accessors

    public Integer getUserProfileId() {
        return this.userProfileId;
    }
    
    public void setUserProfileId(Integer userProfileId) {
        this.userProfileId = userProfileId;
    }

    public Integer getDisabilityId() {
        return this.disabilityId;
    }
    
    public void setDisabilityId(Integer disabilityId) {
        this.disabilityId = disabilityId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserProfileHasDisabilityId) ) return false;
		 UserProfileHasDisabilityId castOther = ( UserProfileHasDisabilityId ) other; 
         
		 return ( (this.getUserProfileId()==castOther.getUserProfileId()) || ( this.getUserProfileId()!=null && castOther.getUserProfileId()!=null && this.getUserProfileId().equals(castOther.getUserProfileId()) ) )
 && ( (this.getDisabilityId()==castOther.getDisabilityId()) || ( this.getDisabilityId()!=null && castOther.getDisabilityId()!=null && this.getDisabilityId().equals(castOther.getDisabilityId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserProfileId() == null ? 0 : this.getUserProfileId().hashCode() );
         result = 37 * result + ( getDisabilityId() == null ? 0 : this.getDisabilityId().hashCode() );
         return result;
   }   





}