package org.bentoweb.amfortas.hibernate.om;



/**
 * UserUsesOsSettingId generated by hbm2java
 */

public class UserUsesOsSettingId  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 7177877899030476161L;
	private Integer userUsesOsId;
     private Integer operatingSystemSettingId;


    // Constructors

    /** default constructor */
    public UserUsesOsSettingId() {
    }
    

    

   
    // Property accessors

    public Integer getUserUsesOsId() {
        return this.userUsesOsId;
    }
    
    public void setUserUsesOsId(Integer userUsesOsId) {
        this.userUsesOsId = userUsesOsId;
    }

    public Integer getOperatingSystemSettingId() {
        return this.operatingSystemSettingId;
    }
    
    public void setOperatingSystemSettingId(Integer operatingSystemSettingId) {
        this.operatingSystemSettingId = operatingSystemSettingId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserUsesOsSettingId) ) return false;
		 UserUsesOsSettingId castOther = ( UserUsesOsSettingId ) other; 
         
		 return ( (this.getUserUsesOsId()==castOther.getUserUsesOsId()) || ( this.getUserUsesOsId()!=null && castOther.getUserUsesOsId()!=null && this.getUserUsesOsId().equals(castOther.getUserUsesOsId()) ) )
 && ( (this.getOperatingSystemSettingId()==castOther.getOperatingSystemSettingId()) || ( this.getOperatingSystemSettingId()!=null && castOther.getOperatingSystemSettingId()!=null && this.getOperatingSystemSettingId().equals(castOther.getOperatingSystemSettingId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserUsesOsId() == null ? 0 : this.getUserUsesOsId().hashCode() );
         result = 37 * result + ( getOperatingSystemSettingId() == null ? 0 : this.getOperatingSystemSettingId().hashCode() );
         return result;
   }   





}