package org.bentoweb.amfortas.hibernate.om;

import java.util.Set;


/**
 * UserUsesUserAgent generated by hbm2java
 */

public class UserUsesUserAgent  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 7074862864517360007L;
	private Integer userUsesUaId;
     private TestProfile testProfile;
     private UserAgent userAgent;
     private AtExperience atExperience;
     private String version;
     private String browserOther;
     private Set userUsesUaPlugins;
     private Set userUsesUaSettings;


    // Constructors

    /** default constructor */
    public UserUsesUserAgent() {
    }
    
    /** constructor with id */
    public UserUsesUserAgent(Integer userUsesUaId) {
        this.userUsesUaId = userUsesUaId;
    }

    

   
    // Property accessors

    public Integer getUserUsesUaId() {
        return this.userUsesUaId;
    }
    
    public void setUserUsesUaId(Integer userUsesUaId) {
        this.userUsesUaId = userUsesUaId;
    }

    public TestProfile getTestProfile() {
        return this.testProfile;
    }
    
    public void setTestProfile(TestProfile testProfile) {
        this.testProfile = testProfile;
    }

    public UserAgent getUserAgent() {
        return this.userAgent;
    }
    
    public void setUserAgent(UserAgent userAgent) {
        this.userAgent = userAgent;
    }

    public AtExperience getAtExperience() {
        return this.atExperience;
    }
    
    public void setAtExperience(AtExperience atExperience) {
        this.atExperience = atExperience;
    }

    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }

    public String getBrowserOther() {
        return this.browserOther;
    }
    
    public void setBrowserOther(String browserOther) {
        this.browserOther = browserOther;
    }

    public Set getUserUsesUaPlugins() {
        return this.userUsesUaPlugins;
    }
    
    public void setUserUsesUaPlugins(Set userUsesUaPlugins) {
        this.userUsesUaPlugins = userUsesUaPlugins;
    }

    public Set getUserUsesUaSettings() {
        return this.userUsesUaSettings;
    }
    
    public void setUserUsesUaSettings(Set userUsesUaSettings) {
        this.userUsesUaSettings = userUsesUaSettings;
    }
   








}