package org.bentoweb.amfortas.hibernate.om;

import java.util.Set;


/**
 * UserAgent generated by hbm2java
 */

public class UserAgent  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -5339718645997897379L;
	private Integer userAgentId;
     private UserAgentTypes userAgentTypes;
     private String nameKey;
     private String nameDefault;
     private String vendor;
     private boolean visible;
     private Set userUsesUserAgents;


    // Constructors

    /** default constructor */
    public UserAgent() {
    }
    
    /** constructor with id */
    public UserAgent(Integer userAgentId) {
        this.userAgentId = userAgentId;
    }

    

   
    // Property accessors

    public Integer getUserAgentId() {
        return this.userAgentId;
    }
    
    public void setUserAgentId(Integer userAgentId) {
        this.userAgentId = userAgentId;
    }

    public UserAgentTypes getUserAgentTypes() {
        return this.userAgentTypes;
    }
    
    public void setUserAgentTypes(UserAgentTypes userAgentTypes) {
        this.userAgentTypes = userAgentTypes;
    }

    public String getNameKey() {
        return this.nameKey;
    }
    
    public void setNameKey(String nameKey) {
        this.nameKey = nameKey;
    }

    public String getNameDefault() {
        return this.nameDefault;
    }
    
    public void setNameDefault(String nameDefault) {
        this.nameDefault = nameDefault;
    }

    public String getVendor() {
        return this.vendor;
    }
    
    public void setVendor(String vendor) {
        this.vendor = vendor;
    }

    public boolean isVisible() {
        return this.visible;
    }
    
    public void setVisible(boolean visible) {
        this.visible = visible;
    }

    public Set getUserUsesUserAgents() {
        return this.userUsesUserAgents;
    }
    
    public void setUserUsesUserAgents(Set userUsesUserAgents) {
        this.userUsesUserAgents = userUsesUserAgents;
    }
   








}