package org.bentoweb.amfortas.hibernate.om;



/**
 * Yesnoopenquestion generated by hbm2java
 */

public class Yesnoopenquestion  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -3073952610161590153L;
	private Integer yesnoopenId;
     private Testresult testresult;
     private Integer choice;
     private String text;


    // Constructors

    /** default constructor */
    public Yesnoopenquestion() {
    }
    
    /** constructor with id */
    public Yesnoopenquestion(Integer yesnoopenId) {
        this.yesnoopenId = yesnoopenId;
    }

    

   
    // Property accessors

    public Integer getYesnoopenId() {
        return this.yesnoopenId;
    }
    
    public void setYesnoopenId(Integer yesnoopenId) {
        this.yesnoopenId = yesnoopenId;
    }

    public Testresult getTestresult() {
        return this.testresult;
    }
    
    public void setTestresult(Testresult testresult) {
        this.testresult = testresult;
    }

    public Integer getChoice() {
        return this.choice;
    }
    
    public void setChoice(Integer choice) {
        this.choice = choice;
    }

    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
   








}