package org.bentoweb.amfortas.hibernate.om;



/**
 * Yesnoquestion generated by hbm2java
 */

public class Yesnoquestion  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -6615925896252903746L;
	private Integer yesnoId;
     private Testresult testresult;
     private Integer choice;


    // Constructors

    /** default constructor */
    public Yesnoquestion() {
    }
    
    /** constructor with id */
    public Yesnoquestion(Integer yesnoId) {
        this.yesnoId = yesnoId;
    }

    

   
    // Property accessors

    public Integer getYesnoId() {
        return this.yesnoId;
    }
    
    public void setYesnoId(Integer yesnoId) {
        this.yesnoId = yesnoId;
    }

    public Testresult getTestresult() {
        return this.testresult;
    }
    
    public void setTestresult(Testresult testresult) {
        this.testresult = testresult;
    }

    public Integer getChoice() {
        return this.choice;
    }
    
    public void setChoice(Integer choice) {
        this.choice = choice;
    }
   








}